##
## Kbuild
##
## History:
##    2009/07/09 - [Anthony Ginger] Create
##
## Copyright (C) 2004-2008, Ambarella, Inc.
##
## All rights reserved. No Part of this file may be reproduced, stored
## in a retrieval system, or transmitted, in any form, or by any means,
## electronic, mechanical, photocopying, recording, or otherwise,
## without the prior consent of Ambarella, Inc.
##

EXTRA_CFLAGS		+= $(AMBARELLA_DRV_CFLAGS) -I$(AMB_TOPDIR)/kernel/private/drivers/vin
EXTRA_AFLAGS		+= $(AMBARELLA_DRV_AFLAGS)
EXTRA_LDFLAGS		+= $(AMBARELLA_DRV_LDFLAGS)

# include $(AMB_TOPDIR)/.config

ifeq ($(CONFIG_SENSOR_MT9P401), y)
obj-m := mt9p401.o
mt9p401-y := mt9p001.o
endif

ifeq ($(CONFIG_SENSOR_MT9P031) , y)
obj-m := mt9p031.o
mt9p031-y := mt9p001.o
endif

ifeq ($(CONFIG_SENSOR_MT9P001), y)
obj-m := mt9p001.o
endif

