##
## Kbuild
##
## History:
##    2011/06/17 - [Haowei Lo] Create
##
## Copyright (C) 2004-2011, Ambarella, Inc.
##
## All rights reserved. No Part of this file may be reproduced, stored
## in a retrieval system, or transmitted, in any form, or by any means,
## electronic, mechanical, photocopying, recording, or otherwise,
## without the prior consent of Ambarella, Inc.
##

EXTRA_CFLAGS		+= $(AMBARELLA_DRV_CFLAGS) -I$(AMB_TOPDIR)/kernel/private/drivers/vin/sbrg
EXTRA_AFLAGS		+= $(AMBARELLA_DRV_AFLAGS)
EXTRA_LDFLAGS		+= $(AMBARELLA_DRV_LDFLAGS)

obj-m := sbrg.o
sbrg-y := sbrg_dev_s3d_drv.o sbrg_core.o

