##
## Kbuild
##
## History:
##    2012/01/16 - [Cao Rongrong] Create
##
## Copyright (C) 2011-2015, Ambarella, Inc.
##
## All rights reserved. No Part of this file may be reproduced, stored
## in a retrieval system, or transmitted, in any form, or by any means,
## electronic, mechanical, photocopying, recording, or otherwise,
## without the prior consent of Ambarella, Inc.
##

obj-m := ambad.o
ambad-y := ambad_bin.o

