# AMBARELLA Platform Support
snd-soc-ambarella-objs := ambarella_pcm.o
snd-soc-ambarella-i2s-objs := ambarella_i2s.o

obj-$(CONFIG_SND_AMBARELLA_SOC)		+= snd-soc-ambarella.o
obj-$(CONFIG_SND_AMBARELLA_SOC_I2S)	+= snd-soc-ambarella-i2s.o

# AMBARELLA Machine Support
snd-soc-ipcam-objs := ipcam.o
snd-soc-ambevk-objs := ambevk.o
snd-soc-i1evk-objs := i1evk.o
snd-soc-md800-objs := md800.o
snd-soc-dummy-objs := dummy.o
snd-soc-a5spa2-objs := a5spa2.o
snd-soc-ambxman-objs := ambxman.o
snd-soc-ambfm34-objs := ambfm34.o
snd-soc-ambcloudcam-objs := ambcloudcam.o
snd-soc-dvw-objs   := dvw101.o
snd-soc-ambh20-objs := ambh20.o

obj-$(CONFIG_IPCAM_BOARD)		+= snd-soc-ipcam.o
obj-$(CONFIG_AMBEVK_BOARD)		+= snd-soc-ambevk.o
obj-$(CONFIG_I1EVK_BOARD)		+= snd-soc-i1evk.o
obj-$(CONFIG_MD800_BOARD)		+= snd-soc-md800.o
obj-$(CONFIG_AMBARELLA_DUMMY_BOARD)	+= snd-soc-dummy.o
obj-$(CONFIG_A5S_PA2_BOARD)		+= snd-soc-a5spa2.o
obj-$(CONFIG_A5S_XMAN_BOARD)	+= snd-soc-ambxman.o
obj-$(CONFIG_A5S_FM34_BOARD)	+= snd-soc-ambfm34.o
obj-$(CONFIG_A5S_CLOUDCAM_BOARD)	+= snd-soc-ambcloudcam.o
obj-$(CONFIG_DVW_BOARD)			+= snd-soc-dvw.o
obj-$(CONFIG_AMBH20_BOARD)		+= snd-soc-ambh20.o
