##
## playback/amf/injector/make.inc
##
## History:
##    2013/05/27 - [Roy Su] Created file
##
## Copyright (C) 2011-2015, Ambarella, Inc.
##
## All rights reserved. No Part of this file may be reproduced, stored
## in a retrieval system, or transmitted, in any form, or by any means,
## electronic, mechanical, photocopying, recording, or otherwise,
## without the prior consent of Ambarella, Inc.
##

ifeq ($(BUILD_PLAYBACK_AMF), y)

include $(call all-subdir-makefiles)

endif
