#ifndef AMBAS_IMGPROC_IOCTL_ARCH_H
#define AMBAS_IMGPROC_IOCTL_ARCH_H

#include <linux/ioctl.h>

/*
 * image processing APIs	- 'p'
 */
#define	IAV_IOC_IMAGE_MAGIC		'p'

#define	_IMG_IO(IOCTL)				_IO(IAV_IOC_IMAGE_MAGIC, IOCTL)
#define	_IMG_IOW(IOCTL, param)		_IOW(IAV_IOC_IMAGE_MAGIC, IOCTL, param)
#define	_IMG_IOR(IOCTL, param)		_IOR(IAV_IOC_IMAGE_MAGIC, IOCTL, param)
#define	_IMG_IOWR(IOCTL, param)	_IOWR(IAV_IOC_IMAGE_MAGIC, IOCTL, param)

enum {
	IOC_IMG_CONFIG_STATISTICS = 0x01,
	IOC_IMG_GET_STATISTICS = 0x02,
	IOC_IMG_CONFIG_FLOAT_STATISTICS = 0x03,
	IOC_IMG_NOISE_FILTER_SETUP = 0x04,
	IOC_IMG_BLACK_LEVEL_GLOBAL_OFFSET = 0x05,
	IOC_IMG_BAD_PIXEL_CORRECTION = 0x06,
	IOC_IMG_CFA_LEAKAGE_FILTER_SETUP = 0x07,
	IOC_IMG_CFA_NOISE_FILTER_SETUP = 0x08,
	IOC_IMG_RGB_GAIN_ADJUST = 0x09,
	IOC_IMG_VIGNETTE_COMPENSATION = 0x0A,
	IOC_IMG_LOCAL_EXPOSURE = 0x0B,
	IOC_IMG_COLOR_CORRECTION = 0x0C,
	IOC_IMG_RGB_TO_YUV_SETUP = 0x0D,
	IOC_IMG_CHROMA_SCALE = 0x0E,
	IOC_IMG_CHROMA_MEDIAN_FILTER_SETUP = 0x0F,
	IOC_IMG_CHROMA_NOISE_FILTER_SETUP = 0x10,
	IOC_IMG_LUMA_SHARPENING = 0x11,
	IOC_IMG_LUMA_SHARPENING_FIR_CONFIG = 0x12,
	IOC_IMG_LUMA_SHARPENING_BLEND_CONFIG = 0x13,
	IOC_IMG_LUMA_SHARPENING_LEVEL_CONTROL = 0x14,
	IOC_IMG_LUMA_SHARPENING_LNL = 0x15,
	IOC_IMG_MCTF_GMV_SETUP = 0x16,
	IOC_IMG_MCTF_MV_STABILIZER_SETUP = 0x17,
	IOC_IMG_AAA_SETUP_EX = 0x18,
	IOC_IMG_ANTI_ALIASING_CONFIG = 0x19,
	IOC_IMG_DIGITAL_SATURATION_LEVEL = 0x1A,
	IOC_IMG_SET_ZOOM_FACTOR = 0x1B,
	IOC_IMG_DEMOSAIC_CONIFG = 0x1C,
	IOC_IMG_SENSOR_CONFIG = 0x1D,
	IOC_IMG_STATIC_BAD_PIXEL_CORRECTION = 0x1E,
	IOC_IMG_SET_BLACK_LVL_STATE_TABLE = 0x1F,
	IOC_IMG_CONFIG_HISTOGRAM = 0x20,

	IOC_IMG_HDR_SET_VIDEO_PROC = 0x30,
	IOC_IMG_HDR_START_CMD_BLOCK = 0x31,
	IOC_IMG_HDR_END_CMD_BLOCK = 0x32,
	IOC_IMG_HDR_BL_GLOBAL_OFFSET = 0x33,
	IOC_IMG_HDR_CFA_NF = 0x34,
	IOC_IMG_HDR_LE = 0x35,
	IOC_IMG_HDR_MIXER = 0x36,
	IOC_IMG_HDR_ALPHA_MAP = 0x37,
	IOC_IMG_VCAP_NO_OP = 0x38,
	IOC_IMG_HDR_CC = 0x39,
	IOC_IMG_HDR_RGB_GAIN_ADJUST = 0x3A,
	IOC_IMG_HDR_SET_ROW_OFFSET = 0x3B,
	IOC_IMG_HDR_YUV_CNTL_PARAM = 0x3C,
	IOC_IMG_HDR_YUV_CNTL_INIT = 0x3D,
	IOC_IMG_HDR_BPC = 0x3E,
	IOC_IMG_HDR_ANTI_ALIASING = 0x3F,
	IOC_IMG_HDR_CFA_LEAKAGE = 0x40,

	IOC_IMG_CONFIG_FLOAT_STATISTICS_NI = 0x80,
	IOC_IMG_NOISE_FILTER_SETUP_NI = 0x81,
	IOC_IMG_BLACK_LEVEL_GLOBAL_OFFSET_NI = 0x82,
	IOC_IMG_BAD_PIXEL_CORRECTION_NI = 0x83,
	IOC_IMG_CFA_LEAKAGE_FILTER_SETUP_NI = 0x84,
	IOC_IMG_CFA_NOISE_FILTER_SETUP_NI = 0x85,
	IOC_IMG_RGB_GAIN_ADJUST_NI = 0x86,
	IOC_IMG_VIGNETTE_COMPENSATION_NI = 0x87,
	IOC_IMG_LOCAL_EXPOSURE_NI = 0x88,
	IOC_IMG_COLOR_CORRECTION_NI = 0x89,
	IOC_IMG_RGB_TO_YUV_SETUP_NI = 0x8A,
	IOC_IMG_CHROMA_SCALE_NI = 0x8B,
	IOC_IMG_CHROMA_MEDIAN_FILTER_SETUP_NI = 0x8C,
	IOC_IMG_CHROMA_NOISE_FILTER_SETUP_NI = 0x8D,
	IOC_IMG_LUMA_SHARPENING_NI = 0x8E,
	IOC_IMG_LUMA_SHARPENING_FIR_CONFIG_NI = 0x8F,
	IOC_IMG_LUMA_SHARPENING_BLEND_CNTL_NI = 0x90,
	IOC_IMG_LUMA_SHARPENING_LEVEL_CONTROL_NI = 0x91,
	IOC_IMG_LUMA_SHARPENING_TONE_NI = 0x92,
	IOC_IMG_LUMA_SHARPENING_LNL_NI = 0x93,
	IOC_IMG_MCTF_GMV_SETUP_NI = 0x94,
	IOC_IMG_MCTF_MV_STABILIZER_SETUP_NI = 0x95,
	IOC_IMG_AAA_SETUP_EX_NI = 0x96,
	IOC_IMG_ANTI_ALIASING_CONFIG_NI = 0x97,
	IOC_IMG_DIGITAL_SATURATION_LEVEL_NI = 0x98,
	IOC_IMG_DEMOSAIC_CONIFG_NI = 0x99,
	IOC_IMG_SENSOR_CONFIG_NI = 0x9A,
	IOC_IMG_STATIC_BAD_PIXEL_CORRECTION_NI = 0x9B,
	IOC_IMG_SET_BLACK_LVL_STATE_TABLE_NI = 0x9C,
	IOC_IMG_STRONG_GRGB_MISMATCH_NI = 0x9D,
	IOC_IMG_GET_PHY_START_NI = 0x9E,
	IOC_IMG_SET_USER_START_NI = 0x9F,
	IOC_IMG_RESET_RAW2ENC_NI = 0xA0,
	IOC_IMG_WAIT_RAW2ENC_NI = 0xA1,
	IOC_IMG_FEED_RAW_NI = 0xA2,
	IOC_IMG_SET_HISO_CFG_NI = 0xA3,
	IOC_IMG_UPDATE_HISO_CFG_NI = 0xA4,
	IOC_IMG_CONFIG_STATISTICS_NI = 0xA5,
	IOC_IMG_HISO_TIMING = 0xA6,
	IOC_IMG_WAIT_ENTER_PREVIEW = 0xA7,

	//for debug, start from 0xE0
	IOC_IMG_DUMP_IDSP_SEC = 0xE0,
	IOC_IMG_CANCEL_GETTING_STATISTICS =0xE1,

};

#define	IAV_IOC_IMG_CONFIG_STATISTICS				_IMG_IOW(IOC_IMG_CONFIG_STATISTICS, struct aaa_statistics_config*)
#define	IAV_IOC_IMG_GET_STATISTICS				_IMG_IOR(IOC_IMG_GET_STATISTICS, struct img_statistics*)
#define	IAV_IOC_IMG_CONFIG_FLOAT_STATISTICS			_IMG_IOW(IOC_IMG_CONFIG_FLOAT_STATISTICS, struct aaa_floating_tile_config_info*)
#define	IAV_IOC_IMG_CONFIG_HISTOGRAM				_IMG_IOW(IOC_IMG_CONFIG_HISTOGRAM, struct aaa_histogram_config *)
#define	IAV_IOC_IMG_NOISE_FILTER_SETUP				_IMG_IOW(IOC_IMG_NOISE_FILTER_SETUP, u32)
#define	IAV_IOC_IMG_BLACK_LEVEL_GLOBAL_OFFSET			_IMG_IOW(IOC_IMG_BLACK_LEVEL_GLOBAL_OFFSET, struct black_level_global_offset*)
#define	IAV_IOC_IMG_BAD_PIXEL_CORRECTION			_IMG_IOW(IOC_IMG_BAD_PIXEL_CORRECTION, struct bad_pixel_correct_info*)
#define	IAV_IOC_IMG_CFA_LEAKAGE_FILTER_SETUP			_IMG_IOW(IOC_IMG_CFA_LEAKAGE_FILTER_SETUP, struct cfa_leakage_filter_info*)
#define	IAV_IOC_IMG_CFA_NOISE_FILTER_SETUP			_IMG_IOW(IOC_IMG_CFA_NOISE_FILTER_SETUP, struct cfa_noise_filter_info*)
#define	IAV_IOC_IMG_VIGNETTE_COMPENSATION			_IMG_IOW(IOC_IMG_VIGNETTE_COMPENSATION, struct vignette_compensation_info*)
#define	IAV_IOC_IMG_LOCAL_EXPOSURE				_IMG_IOW(IOC_IMG_LOCAL_EXPOSURE, struct local_exposure_info*)
#define	IAV_IOC_IMG_COLOR_CORRECTION				_IMG_IOW(IOC_IMG_COLOR_CORRECTION, struct color_correction_info*)
#define	IAV_IOC_IMG_RGB_TO_YUV_SETUP				_IMG_IOW(IOC_IMG_RGB_TO_YUV_SETUP, struct rgb_to_yuv_info*)
#define	IAV_IOC_IMG_CHROMA_SCALE				_IMG_IOW(IOC_IMG_CHROMA_SCALE, struct chroma_scale_info*)
#define	IAV_IOC_IMG_CHROMA_MEDIAN_FILTER_SETUP			_IMG_IOW(IOC_IMG_CHROMA_MEDIAN_FILTER_SETUP, struct chroma_median_filter*)
#define	IAV_IOC_IMG_CHROMA_NOISE_FILTER_SETUP			_IMG_IOW(IOC_IMG_CHROMA_NOISE_FILTER_SETUP, struct chroma_noise_filter_info*)
#define	IAV_IOC_IMG_LUMA_SHARPENING				_IMG_IOW(IOC_IMG_LUMA_SHARPENING, struct luma_sharpening_info*)
#define	IAV_IOC_IMG_LUMA_SHARPENING_FIR_CONFIG			_IMG_IOW(IOC_IMG_LUMA_SHARPENING_FIR_CONFIG, struct luma_sharp_fir_info*)
#define	IAV_IOC_IMG_LUMA_SHARPENING_BLEND_CONFIG		_IMG_IOW(IOC_IMG_LUMA_SHARPENING_BLEND_CONFIG, struct luma_sharp_blend_info*)
#define	IAV_IOC_IMG_LUMA_SHARPENING_LEVEL_CONTROL		_IMG_IOW(IOC_IMG_LUMA_SHARPENING_LEVEL_CONTROL, struct luma_sharp_level_info*)
#define	IAV_IOC_IMG_LUMA_SHARPENING_LNL				_IMG_IOW(IOC_IMG_LUMA_SHARPENING_LNL, struct luma_sharp_lnl_info*)
#define	IAV_IOC_IMG_MCTF_GMV_SETUP				_IMG_IOW(IOC_IMG_MCTF_GMV_SETUP, struct mctf_gmv_info*)
#define	IAV_IOC_IMG_MCTF_MV_STABILIZER_SETUP			_IMG_IOW(IOC_IMG_MCTF_MV_STABILIZER_SETUP, struct mctf_mv_stab_info*)
#define	IAV_IOC_IMG_RGB_GAIN_ADJUST				_IMG_IOW(IOC_IMG_RGB_GAIN_ADJUST, struct rgb_gain_info*)
#define	IAV_IOC_IMG_AAA_SETUP_EX				_IMG_IOW(IOC_IMG_AAA_SETUP_EX, struct aaa_statistics_ex*)
#define	IAV_IOC_IMG_ANTI_ALIASING_CONFIG			_IMG_IOW(IOC_IMG_ANTI_ALIASING_CONFIG, struct anti_aliasing_info*)
#define	IAV_IOC_IMG_DIGITAL_SATURATION_LEVEL			_IMG_IOW(IOC_IMG_DIGITAL_SATURATION_LEVEL, struct digital_gain_level*)
#define	IAV_IOC_IMG_SET_ZOOM_FACTOR				_IMG_IOW(IOC_IMG_SET_ZOOM_FACTOR, struct zoom_factor_info*)
#define	IAV_IOC_IMG_DEMOSAIC_CONIFG				_IMG_IOW(IOC_IMG_DEMOSAIC_CONIFG, struct demoasic_filter_info*)
#define	IAV_IOC_IMG_SENSOR_CONFIG				_IMG_IOW(IOC_IMG_SENSOR_CONFIG, struct sensor_info*)
#define	IAV_IOC_IMG_STATIC_BAD_PIXEL_CORRECTION			_IMG_IOW(IOC_IMG_STATIC_BAD_PIXEL_CORRECTION, struct fixed_pattern_correct*)
#define	IAV_IOC_IMG_SET_BLACK_LVL_STATE_TABLE			_IMG_IOW(IOC_IMG_SET_BLACK_LVL_STATE_TABLE,struct black_level_state*)

#define	IAV_IOC_IMG_DUMP_IDSP_SEC				_IMG_IOWR(IOC_IMG_DUMP_IDSP_SEC, iav_idsp_config_info_t *)
#define   IAV_IOC_IMG_CANCEL_GETTING_STATISTICS	 _IMG_IO(IOC_IMG_CANCEL_GETTING_STATISTICS)

#define	IAV_IOC_IMG_HDR_SET_VIDEO_PROC				_IMG_IOW(IOC_IMG_HDR_SET_VIDEO_PROC, struct video_hdr_proc_control *)
#define	IAV_IOC_IMG_HDR_START_CMD_BLOCK				_IMG_IOW(IOC_IMG_HDR_START_CMD_BLOCK, u32)
#define	IAV_IOC_IMG_HDR_END_CMD_BLOCK				_IMG_IOW(IOC_IMG_HDR_END_CMD_BLOCK, u32)
#define	IAV_IOC_IMG_HDR_BL_GLOBAL_OFFSET			_IMG_IOW(IOC_IMG_HDR_BL_GLOBAL_OFFSET, struct black_level_global_offset *)
#define	IAV_IOC_IMG_HDR_CFA_NF					_IMG_IOW(IOC_IMG_HDR_CFA_NF, struct cfa_noise_filter_info *)
#define	IAV_IOC_IMG_HDR_LE					_IMG_IOW(IOC_IMG_HDR_LE, struct local_exposure_info *)
#define	IAV_IOC_IMG_HDR_MIXER					_IMG_IOW(IOC_IMG_HDR_MIXER, struct hdr_mixer_info *)
#define	IAV_IOC_IMG_HDR_ALPHA_MAP				_IMG_IOW(IOC_IMG_HDR_ALPHA_MAP, struct color_correction_info*)
#define	IAV_IOC_IMG_VCAP_NO_OP					_IMG_IOW(IOC_IMG_VCAP_NO_OP, struct vcap_no_op *)
#define	IAV_IOC_IMG_HDR_CC					_IMG_IOW(IOC_IMG_HDR_CC, struct color_correction_info*)
#define	IAV_IOC_IMG_HDR_RGB_GAIN_ADJUST				_IMG_IOW(IOC_IMG_HDR_RGB_GAIN_ADJUST, struct rgb_gain_info*)
#define	IAV_IOC_IMG_HDR_SET_ROW_OFFSET				_IMG_IOW(IOC_IMG_HDR_SET_ROW_OFFSET, struct video_hdr_proc_control*)
#define	IAV_IOC_IMG_HDR_YUV_CNTL_PARAM				_IMG_IOW(IOC_IMG_HDR_YUV_CNTL_PARAM, struct video_hdr_yuv_cntl_param*)
#define	IAV_IOC_IMG_HDR_BPC					_IMG_IOW(IOC_IMG_HDR_BPC, struct bad_pixel_correct_info*)
#define	IAV_IOC_IMG_HDR_ANTI_ALIASING			_IMG_IOW(IOC_IMG_HDR_ANTI_ALIASING, struct anti_aliasing_info*)
#define	IAV_IOC_IMG_HDR_CFA_LEAKAGE			_IMG_IOW(IOC_IMG_HDR_CFA_LEAKAGE, struct cfa_leakage_filter_info*)

#define	IAV_IOC_IMG_CONFIG_FLOAT_STATISTICS_NI                 	_IMG_IOW(IOC_IMG_CONFIG_FLOAT_STATISTICS_NI, struct aaa_floating_tile_config_info*)
#define	IAV_IOC_IMG_NOISE_FILTER_SETUP_NI                      	_IMG_IOW(IOC_IMG_NOISE_FILTER_SETUP_NI, u32)
#define	IAV_IOC_IMG_BLACK_LEVEL_GLOBAL_OFFSET_NI               	_IMG_IOW(IOC_IMG_BLACK_LEVEL_GLOBAL_OFFSET_NI, black_level_global_offset_t*)
#define	IAV_IOC_IMG_BAD_PIXEL_CORRECTION_NI                    	_IMG_IOW(IOC_IMG_BAD_PIXEL_CORRECTION_NI, bad_pixel_correct_setup_t*)
#define	IAV_IOC_IMG_CFA_LEAKAGE_FILTER_SETUP_NI                	_IMG_IOW(IOC_IMG_CFA_LEAKAGE_FILTER_SETUP_NI, cfa_domain_leakage_filter_t*)
#define	IAV_IOC_IMG_CFA_NOISE_FILTER_SETUP_NI                  	_IMG_IOW(IOC_IMG_CFA_NOISE_FILTER_SETUP_NI, cfa_noise_filter_t*)
#define	IAV_IOC_IMG_RGB_GAIN_ADJUST_NI                         	_IMG_IOW(IOC_IMG_RGB_GAIN_ADJUST_NI, rgb_gain_adjust_t*)
#define	IAV_IOC_IMG_VIGNETTE_COMPENSATION_NI                   	_IMG_IOW(IOC_IMG_VIGNETTE_COMPENSATION_NI, struct vignette_compensation_info*)
#define	IAV_IOC_IMG_LOCAL_EXPOSURE_NI                          	_IMG_IOW(IOC_IMG_LOCAL_EXPOSURE_NI, local_exposure_t*)
#define	IAV_IOC_IMG_COLOR_CORRECTION_NI                        	_IMG_IOW(IOC_IMG_COLOR_CORRECTION_NI, color_correction_t*)
#define	IAV_IOC_IMG_RGB_TO_YUV_SETUP_NI                        	_IMG_IOW(IOC_IMG_RGB_TO_YUV_SETUP_NI, rgb_to_yuv_setup_t*)
#define	IAV_IOC_IMG_CHROMA_SCALE_NI                            	_IMG_IOW(IOC_IMG_CHROMA_SCALE_NI, chroma_scale_t*)
#define	IAV_IOC_IMG_CHROMA_MEDIAN_FILTER_SETUP_NI              	_IMG_IOW(IOC_IMG_CHROMA_MEDIAN_FILTER_SETUP_NI, chroma_median_filter_info_t*)
#define	IAV_IOC_IMG_CHROMA_NOISE_FILTER_SETUP_NI               	_IMG_IOW(IOC_IMG_CHROMA_NOISE_FILTER_SETUP_NI, chroma_noise_filter_t*)
#define	IAV_IOC_IMG_LUMA_SHARPENING_NI                         	_IMG_IOW(IOC_IMG_LUMA_SHARPENING_NI, luma_sharpening_t*)
#define	IAV_IOC_IMG_LUMA_SHARPENING_FIR_CONFIG_NI              	_IMG_IOW(IOC_IMG_LUMA_SHARPENING_FIR_CONFIG_NI, luma_sharpening_FIR_config_t*)
#define	IAV_IOC_IMG_LUMA_SHARPENING_BLEND_CNTL_NI            	_IMG_IOW(IOC_IMG_LUMA_SHARPENING_BLEND_CNTL_NI, luma_sharpening_blend_control_t*)
#define	IAV_IOC_IMG_LUMA_SHARPENING_LEVEL_CONTROL_NI           	_IMG_IOW(IOC_IMG_LUMA_SHARPENING_LEVEL_CONTROL_NI, luma_sharpening_level_control_t*)
#define	IAV_IOC_IMG_LUMA_SHARPENING_TONE_NI                    	_IMG_IOW(IOC_IMG_LUMA_SHARPENING_TONE_NI, luma_sharpening_tone_control_t*)
#define	IAV_IOC_IMG_LUMA_SHARPENING_LNL_NI                     	_IMG_IOW(IOC_IMG_LUMA_SHARPENING_LNL_NI, luma_sharpening_LNL_t*)
#define	IAV_IOC_IMG_MCTF_GMV_SETUP_NI                          	_IMG_IOW(IOC_IMG_MCTF_GMV_SETUP_NI, VCAP_MCTF_GMV_CMD*)
#define	IAV_IOC_IMG_MCTF_MV_STABILIZER_SETUP_NI                	_IMG_IOW(IOC_IMG_MCTF_MV_STABILIZER_SETUP_NI, VCAP_MCTF_MV_STAB_CMD*)
#define	IAV_IOC_IMG_AAA_SETUP_EX_NI                            	_IMG_IOW(IOC_IMG_AAA_SETUP_EX_NI, struct aaa_statistics_ex*)
#define	IAV_IOC_IMG_ANTI_ALIASING_CONFIG_NI                    	_IMG_IOW(IOC_IMG_ANTI_ALIASING_CONFIG_NI, anti_aliasing_filter_t*)
#define	IAV_IOC_IMG_DIGITAL_SATURATION_LEVEL_NI                	_IMG_IOW(IOC_IMG_DIGITAL_SATURATION_LEVEL_NI, digital_gain_level_t*)
#define	IAV_IOC_IMG_DEMOSAIC_CONIFG_NI                         	_IMG_IOW(IOC_IMG_DEMOSAIC_CONIFG_NI, demoasic_filter_t*)
#define	IAV_IOC_IMG_SENSOR_CONFIG_NI                           	_IMG_IOW(IOC_IMG_SENSOR_CONFIG_NI, sensor_input_setup_t*)
#define	IAV_IOC_IMG_STATIC_BAD_PIXEL_CORRECTION_NI             	_IMG_IOW(IOC_IMG_STATIC_BAD_PIXEL_CORRECTION_NI, fixed_pattern_noise_correct_t*)
#define	IAV_IOC_IMG_SET_BLACK_LVL_STATE_TABLE_NI               	_IMG_IOW(IOC_IMG_SET_BLACK_LVL_STATE_TABLE_NI, black_level_state_table_t*)
#define IAV_IOC_IMG_STRONG_GRGB_MISMATCH_NI			_IMG_IOW(IOC_IMG_STRONG_GRGB_MISMATCH_NI, strong_grgb_mismatch_filter_t*)
#define	IAV_IOC_IMG_GET_PHY_START_NI                           	_IMG_IOR(IOC_IMG_GET_PHY_START_NI, u32*)
#define	IAV_IOC_IMG_SET_USER_START_NI                          	_IMG_IOW(IOC_IMG_SET_USER_START_NI, u32)
#define	IAV_IOC_IMG_RESET_RAW2ENC_NI                           	_IMG_IO(IOC_IMG_RESET_RAW2ENC_NI)
#define	IAV_IOC_IMG_WAIT_RAW2ENC_NI                            	_IMG_IO(IOC_IMG_WAIT_RAW2ENC_NI)
#define	IAV_IOC_IMG_FEED_RAW_NI                                	_IMG_IOW(IOC_IMG_FEED_RAW_NI, struct raw2enc_raw_feed_info*)
#define	IAV_IOC_IMG_SET_HISO_CFG_NI                            	_IMG_IOW(IOC_IMG_SET_HISO_CFG_NI, u8*)
#define	IAV_IOC_IMG_UPDATE_HISO_CFG_NI                         	_IMG_IOW(IOC_IMG_UPDATE_HISO_CFG_NI, VCAP_HISO_CONFIG_UPDATE_CMD*)
#define	IAV_IOC_IMG_CONFIG_STATISTICS_NI			_IMG_IOW(IOC_IMG_CONFIG_STATISTICS_NI, aaa_statistics_setup_t*)
#define IAV_IOC_IMG_HISO_TIMING					_IMG_IO(IOC_IMG_HISO_TIMING)
#define IAV_IOC_IMG_WAIT_ENTER_PREVIEW				_IMG_IO(IOC_IMG_WAIT_ENTER_PREVIEW)

#endif

