##
## Kbuild
##
## History:
##    2010/01/06 - [Qiao Wang] Create
##
## Copyright (C) 2004-2010, Ambarella, Inc.
##
## All rights reserved. No Part of this file may be reproduced, stored
## in a retrieval system, or transmitted, in any form, or by any means,
## electronic, mechanical, photocopying, recording, or otherwise,
## without the prior consent of Ambarella, Inc.
##

EXTRA_CFLAGS		+= $(AMBARELLA_DRV_CFLAGS) -I$(AMB_TOPDIR)/kernel/private/drivers/vin
EXTRA_AFLAGS		+= $(AMBARELLA_DRV_AFLAGS)
EXTRA_LDFLAGS		+= $(AMBARELLA_DRV_LDFLAGS)

obj-m := ov5658_mipi.o
ov5658_mipi-y := ov5658.o

