##
## Kbuild
##
## History:
##    2012/06/28 - [Zhenwu Xue] Create
##
## Copyright (C) 2004-2012, Ambarella, Inc.
##
## All rights reserved. No Part of this file may be reproduced, stored
## in a retrieval system, or transmitted, in any form, or by any means,
## electronic, mechanical, photocopying, recording, or otherwise,
## without the prior consent of Ambarella, Inc.
##

EXTRA_CFLAGS		+= $(AMBARELLA_DRV_CFLAGS)
EXTRA_AFLAGS		+= $(PRIVATE_AFLAGS)
EXTRA_LDFLAGS		+= $(PRIVATE_LDFLAGS)
EXTRA_ARFLAGS		+= $(PRIVATE_ARFLAGS)

obj-m := fdet.o

