##
## Kbuild
##
## History:
##    2012/01/09 - [Jian Tang] Create
##
## Copyright (C) 2012-2016, Ambarella, Inc.
##
## All rights reserved. No Part of this file may be reproduced, stored
## in a retrieval system, or transmitted, in any form, or by any means,
## electronic, mechanical, photocopying, recording, or otherwise,
## without the prior consent of Ambarella, Inc.
##

EXTRA_CFLAGS		+= $(AMBARELLA_DRV_CFLAGS)
EXTRA_AFLAGS		+= $(AMBARELLA_DRV_AFLAGS)
EXTRA_LDFLAGS		+= $(AMBARELLA_DRV_LDFLAGS)

obj-m := iav.o
iav-y := iav_drv.o iav_mem.o iav_vout.o iav_api.o iav_frame.o iav_encode.o \
	iav_decode.o iav_overlay.o iav_still.o iav_test.o iav_timer.o iav_bufcap.o \
	 iav_privmask.o iav_warp.o iav_mem_perf.o iav_pts.o iav_netlink.o
